env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@layout-css/styled-components'
  - react
rules:
  {
    'class-methods-use-this': 'off',
    'function-call-argument-newline': ['error', 'consistent'],
    'global-require': 'off',
    'max-len': ['error', { 'code': 100 }],
    'multiline-ternary': ['error', 'always-multiline'],
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 2 }],
    'no-async-promise-executor': 'off',
    'no-console': 'off',
    'object-property-newline': 'error',
    'radix': 'off',
    'no-underscore-dangle': 'off',
    'no-continue': 'off',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'import/prefer-default-export': 'off',
    'prefer-promise-reject-errors': 'off',
    'react/destructuring-assignment': 'off',
    'react/jsx-filename-extension': 'off',
    'react/no-access-state-in-setstate': 'off',
    'react/prefer-stateless-function': 'warn',
    'react/prop-types': 'off',
    'react/sort-comp': 'off',
    'react/jsx-indent': 'off',
    'quotes': 'off',
  }
